//! Parity test: native PotionEmbedder vs model2vec reference vectors.
//! Reference generated by tests/parity_check.py (model2vec StaticModel,
//! normalize=True) and stored as parity_vectors.npy. Run via
//! `cargo test -p og-core --test potion_parity -- --nocapture` with
//! OG_PARITY_MODEL_DIR + OG_PARITY_VECTORS pointing at the fixtures.

use std::path::Path;

use og_core::model::Embedder as _;

#[test]
fn potion_matches_reference() {
    let dir = match std::env::var("OG_PARITY_MODEL_DIR") {
        Ok(d) => d,
        Err(_) => {
            eprintln!("skipping: OG_PARITY_MODEL_DIR not set");
            return;
        }
    };
    let vec_path = std::env::var("OG_PARITY_VECTORS").expect("OG_PARITY_VECTORS");

    let embedder = og_core::model::potion::PotionEmbedder::load_dir(Path::new(&dir)).unwrap();
    assert_eq!(embedder.dims(), 256);

    let texts = [
        "fn split_identifiers(text: &str) -> String { let extra: Vec<String> = Vec::new(); }",
        "function getUserProfile(request) { return database.query(users); }",
        "error handling retry logic with backoff",
        "pub fn rrf_fuse(channels: &[(f32, Channel)], k: usize) -> Vec<(i64, f32)>",
        "the quick brown fox",
    ];

    let ours = embedder.embed(&texts).unwrap();

    // Read .npy: header is magic + version + header-len + dict; then f32 LE rows.
    let raw = std::fs::read(&vec_path).unwrap();
    let hlen = parse_npy_header_len(&raw).expect("npy header");
    let data = &raw[hlen..];
    let expected: Vec<Vec<f32>> = data
        .chunks_exact(4 * 256)
        .map(|c| {
            c.chunks_exact(4)
                .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
                .collect()
        })
        .collect();

    assert_eq!(expected.len(), ours.len(), "vector count mismatch");

    let mut worst = 0.0f32;
    for (i, (exp, got)) in expected.iter().zip(&ours).enumerate() {
        assert_eq!(exp.len(), got.len());
        let dot: f32 = exp.iter().zip(got.iter()).map(|(a, b)| a * b).sum();
        // Both unit-normalized: dot == cosine. Require > 0.9999.
        let cosine = dot;
        worst = worst.max((1.0 - cosine).abs());
        assert!(cosine > 0.9999, "text {i}: cosine {cosine}");
    }
    eprintln!("parity ok; worst deviation from cosine-1.0: {worst:.6}");
}

/// Minimal .npy header-length parser (magic 6 + ver 2 + u16/u32 len).
fn parse_npy_header_len(raw: &[u8]) -> Option<usize> {
    if raw.len() < 10 || raw[..6] != [0x93, b'N', b'U', b'M', b'P', b'Y'] {
        return None;
    }
    let (major, minor) = (raw[6], raw[7]);
    let len_bytes = match (major, minor) {
        (1, 0) => 2,
        (2, 0) => 4,
        (3, 0) => 4,
        _ => return None,
    };
    let offset = 8;
    let len = match len_bytes {
        2 => u16::from_le_bytes([raw[offset], raw[offset + 1]]) as usize,
        _ => u32::from_le_bytes([
            raw[offset],
            raw[offset + 1],
            raw[offset + 2],
            raw[offset + 3],
        ]) as usize,
    };
    Some(8 + len_bytes + len)
}
